/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.generator.values;

import java.sql.PreparedStatement;

import org.hibernate.engine.jdbc.mutation.JdbcValueBindings;
import org.hibernate.engine.jdbc.mutation.group.PreparedStatementDetails;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.generator.EventType;
import org.hibernate.jdbc.Expectation;
import org.hibernate.sql.model.ast.builder.TableMutationBuilder;

/**
 * Each implementation defines a strategy for retrieving values
 * {@linkplain org.hibernate.generator.OnExecutionGenerator generated by
 * the database} after execution of a mutation statement.
 * <p>
 * An implementation controls:
 * <ul>
 * <li>building the SQL mutation statement, and
 * <li>retrieving the generated values using JDBC.
 * </ul>
 *
 * @see org.hibernate.generator.OnExecutionGenerator
 *
 * @author Marco Belladelli
 */
public interface GeneratedValuesMutationDelegate {
	TableMutationBuilder<?> createTableMutationBuilder(Expectation expectation, SessionFactoryImplementor sessionFactory);

	PreparedStatement prepareStatement(String sql, SharedSessionContractImplementor session);

	/**
	 * Perform the {@code mutation} and extract the database-generated values.
	 *
	 * @see #createTableMutationBuilder
	 */
	GeneratedValues performMutation(
			PreparedStatementDetails statementDetails,
			JdbcValueBindings valueBindings,
			Object entity,
			SharedSessionContractImplementor session);

	/**
	 * Returns the timing this generated values delegate handles.
	 */
	EventType getTiming();

	/**
	 * Returns {@code true} when this delegate supports retrieving arbitrary generated values,
	 * or {@code false} when it only supports identifiers.
	 */
	default boolean supportsArbitraryValues() {
		return false;
	}

	/**
	 * Returns {@code true} when this delegate supports retrieving the {@link org.hibernate.annotations.RowId} value.
	 */
	default boolean supportsRowId() {
		return false;
	}
}
